# !/bin/bash
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS12_4.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS12_17.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS13_2.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS13_8.param -run-solver-solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS14_11.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS14_17.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS15_21.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS15_29.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS16_17.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS16_42.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS17_7.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS17_32.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS18_21.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS18_29.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS19_4.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS19_65.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS20_0.param -run-solver -solver-options "-cpulimit 600"
./savilerow-1.8.0-mac/savilerow lateBindingSolitaire.eprime GeneratedInstances/LBS20_20.param -run-solver -solver-options "-cpulimit 600"
